CREATE VIEW top_contributors AS SELECT NAME
FROM CONTRIBS18
WHERE ENTITY_TP = "IND" AND TRANSACTION_TP IN ("10", "11", "15", "15E", "15J", "22Y")
GROUP BY NAME
ORDER BY SUM(TRANSACTION_AMT) DESC
LIMIT 120

SELECT NAME, CMTE_ID, Sum(TRANSACTION_AMT) as pac_contribs
FROM Contribs18 WHERE Name in (SELECT NAME from top_contributors) AND TRANSACTION_AMT > 100
GROUP BY Name, CMTE_ID
